language: php
addons:
  chrome: stable
  firefox: latest

jobs:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      env: lint=1
    - php: '7.4'
      env: deps=low

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $lint = '1' ]]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.1/php-cs-fixer.phar; fi
  - if [[ $lint = '1' ]]; then wget https://github.com/phpstan/phpstan/releases/download/0.12.8/phpstan.phar; fi

before_script:
  - phpenv config-rm xdebug.ini

install:
  - if [[ $deps = 'low' ]]; then
      composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
    else
      composer update --prefer-dist --no-progress --no-suggest --ansi;
    fi

script:
  - vendor/bin/simple-phpunit
  - if [[ $lint = '1' ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
  - if [[ $lint = '1' ]]; then php phpstan.phar analyse src tests --level=5; fi
